const catchAsyncErrors = require('./catchAsyncErrors')

const isAuthenticateUser = catchAsyncErrors( async(req, res, next) => {

})